added main script

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -19,13 +19,28 @@ jobs:
       - name: Run Jest with coverage
         run: npx jest --coverage --coverageReporters="json-summary"
 
-      - name: Generate coverage badges
-        run: npx jest-coverage-badges output "./badges"
+      - name: Send coverage to API
+        uses: actions/run-script@v1
+        with:
+        script: |
+          set -e  # Exit script immediately on non-zero exit code (error handling)
 
-      - name: Commit and push changes
-        run: |
-          git config --global user.name 'GitHub Actions'
-          git config --global user.email 'actions@users.noreply.github.com'
-          git add badges/*
-          git commit -m "Update coverage badges" || exit 0
-          git push
+          # Retrieve coverage percentage (modify this logic based on your coverage data format)
+          COVERAGE_PERCENTAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
+
+          # Replace with your actual API endpoint URL and any required authorization headers/credentials
+          API_ENDPOINT="http://localhost:3000/badge/addbadge"  # Replace with your actual URL
+
+          curl -X POST -H "Content-Type: application/json" -d '{"coverage": '${COVERAGE_PERCENTAGE}'}' "${API_ENDPOINT}"
+
+
+      # - name: Generate coverage badges
+      #   run: npx jest-coverage-badges output "./badges"
+
+      # - name: Commit and push changes
+      #   run: |
+      #     git config --global user.name 'GitHub Actions'
+      #     git config --global user.email 'actions@users.noreply.github.com'
+      #     git add badges/*
+      #     git commit -m "Update coverage badges" || exit 0
+      #     git push
